/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'frank.zhao' at '4/18/17 11:15 AM' with Gradle 2.14.1
 *
 * @author frank.zhao, @date 4/18/17 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
